
#include <YSI_Coding/y_hooks>

CreateCircle()
{
	circulo[0] = TextDrawCreate(277.500, 417.000, "LD_BEAT:chit");
	TextDrawTextSize(circulo[0], 25.000, 25.000);
	TextDrawAlignment(circulo[0], 1);
	TextDrawColor(circulo[0], 572797951);
	TextDrawSetShadow(circulo[0], 0);
	TextDrawSetOutline(circulo[0], 0);
	TextDrawBackgroundColor(circulo[0], 255);
	TextDrawFont(circulo[0], 4);
	TextDrawSetProportional(circulo[0], 1);
	
	circulo[1] = TextDrawCreate(304.500, 417.000, "LD_BEAT:chit");
	TextDrawTextSize(circulo[1], 25.000, 25.000);
	TextDrawAlignment(circulo[1], 1);
	TextDrawColor(circulo[1], 572797951);
	TextDrawSetShadow(circulo[1], 0);
	TextDrawSetOutline(circulo[1], 0);
	TextDrawBackgroundColor(circulo[1], 255);
	TextDrawFont(circulo[1], 4);
	TextDrawSetProportional(circulo[1], 1);
	
	circulo[2] = TextDrawCreate(331.500, 417.000, "LD_BEAT:chit");
	TextDrawTextSize(circulo[2], 25.000, 25.000);
	TextDrawAlignment(circulo[2], 1);
	TextDrawColor(circulo[2], 572797951);
	TextDrawSetShadow(circulo[2], 0);
	TextDrawSetOutline(circulo[2], 0);
	TextDrawBackgroundColor(circulo[2], 255);
	TextDrawFont(circulo[2], 4);
	TextDrawSetProportional(circulo[2], 1);
	
	circulo[3] = TextDrawCreate(285.000, 424.000, "LD_BEAT:chit");
	TextDrawTextSize(circulo[3], 10.000, 4.000);
	TextDrawAlignment(circulo[3], 1);
	TextDrawColor(circulo[3], -1);
	TextDrawSetShadow(circulo[3], 0);
	TextDrawSetOutline(circulo[3], 0);
	TextDrawBackgroundColor(circulo[3], 255);
	TextDrawFont(circulo[3], 4);
	TextDrawSetProportional(circulo[3], 1);
	
	circulo[4] = TextDrawCreate(285.000, 424.000, "LD_BEAT:chit");
	TextDrawTextSize(circulo[4], 10.000, 4.000);
	TextDrawAlignment(circulo[4], 1);
	TextDrawColor(circulo[4], -1);
	TextDrawSetShadow(circulo[4], 0);
	TextDrawSetOutline(circulo[4], 0);
	TextDrawBackgroundColor(circulo[4], 255);
	TextDrawFont(circulo[4], 4);
	TextDrawSetProportional(circulo[4], 1);
	
	circulo[5] = TextDrawCreate(286.000, 426.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[5], 8.000, 2.000);
	TextDrawAlignment(circulo[5], 1);
	TextDrawColor(circulo[5], -1);
	TextDrawSetShadow(circulo[5], 0);
	TextDrawSetOutline(circulo[5], 0);
	TextDrawBackgroundColor(circulo[5], 255);
	TextDrawFont(circulo[5], 4);
	TextDrawSetProportional(circulo[5], 1);
	
	circulo[6] = TextDrawCreate(286.000, 429.299, "LD_SPAC:white");
	TextDrawTextSize(circulo[6], 8.000, 0.500);
	TextDrawAlignment(circulo[6], 1);
	TextDrawColor(circulo[6], -1);
	TextDrawSetShadow(circulo[6], 0);
	TextDrawSetOutline(circulo[6], 0);
	TextDrawBackgroundColor(circulo[6], 255);
	TextDrawFont(circulo[6], 4);
	TextDrawSetProportional(circulo[6], 1);
	
	circulo[7] = TextDrawCreate(286.000, 431.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[7], 8.000, 2.000);
	TextDrawAlignment(circulo[7], 1);
	TextDrawColor(circulo[7], -1);
	TextDrawSetShadow(circulo[7], 0);
	TextDrawSetOutline(circulo[7], 0);
	TextDrawBackgroundColor(circulo[7], 255);
	TextDrawFont(circulo[7], 4);
	TextDrawSetProportional(circulo[7], 1);
	
	circulo[8] = TextDrawCreate(314.000, 424.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[8], 0.800, 11.000);
	TextDrawAlignment(circulo[8], 1);
	TextDrawColor(circulo[8], -1);
	TextDrawSetShadow(circulo[8], 0);
	TextDrawSetOutline(circulo[8], 0);
	TextDrawBackgroundColor(circulo[8], 255);
	TextDrawFont(circulo[8], 4);
	TextDrawSetProportional(circulo[8], 1);
	
	circulo[9] = TextDrawCreate(314.000, 424.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[9], 5.000, 0.800);
	TextDrawAlignment(circulo[9], 1);
	TextDrawColor(circulo[9], -1);
	TextDrawSetShadow(circulo[9], 0);
	TextDrawSetOutline(circulo[9], 0);
	TextDrawBackgroundColor(circulo[9], 255);
	TextDrawFont(circulo[9], 4);
	TextDrawSetProportional(circulo[9], 1);
	
	circulo[10] = TextDrawCreate(314.000, 435.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[10], 5.000, 0.800);
	TextDrawAlignment(circulo[10], 1);
	TextDrawColor(circulo[10], -1);
	TextDrawSetShadow(circulo[10], 0);
	TextDrawSetOutline(circulo[10], 0);
	TextDrawBackgroundColor(circulo[10], 255);
	TextDrawFont(circulo[10], 4);
	TextDrawSetProportional(circulo[10], 1);
	
	circulo[11] = TextDrawCreate(318.500, 424.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[11], 0.800, 11.000);
	TextDrawAlignment(circulo[11], 1);
	TextDrawColor(circulo[11], -1);
	TextDrawSetShadow(circulo[11], 0);
	TextDrawSetOutline(circulo[11], 0);
	TextDrawBackgroundColor(circulo[11], 255);
	TextDrawFont(circulo[11], 4);
	TextDrawSetProportional(circulo[11], 1);
	
	circulo[12] = TextDrawCreate(316.500, 422.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[12], 0.800, 7.000);
	TextDrawAlignment(circulo[12], 1);
	TextDrawColor(circulo[12], -1);
	TextDrawSetShadow(circulo[12], 0);
	TextDrawSetOutline(circulo[12], 0);
	TextDrawBackgroundColor(circulo[12], 255);
	TextDrawFont(circulo[12], 4);
	TextDrawSetProportional(circulo[12], 1);
	
	circulo[13] = TextDrawCreate(315.500, 431.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[13], 1.299, 1.299);
	TextDrawAlignment(circulo[13], 1);
	TextDrawColor(circulo[13], -1);
	TextDrawSetShadow(circulo[13], 0);
	TextDrawSetOutline(circulo[13], 0);
	TextDrawBackgroundColor(circulo[13], 255);
	TextDrawFont(circulo[13], 4);
	TextDrawSetProportional(circulo[13], 1);
	
	circulo[14] = TextDrawCreate(315.500, 433.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[14], 1.299, 1.299);
	TextDrawAlignment(circulo[14], 1);
	TextDrawColor(circulo[14], -1);
	TextDrawSetShadow(circulo[14], 0);
	TextDrawSetOutline(circulo[14], 0);
	TextDrawBackgroundColor(circulo[14], 255);
	TextDrawFont(circulo[14], 4);
	TextDrawSetProportional(circulo[14], 1);
	
	circulo[15] = TextDrawCreate(316.500, 432.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[15], 1.299, 1.299);
	TextDrawAlignment(circulo[15], 1);
	TextDrawColor(circulo[15], -1);
	TextDrawSetShadow(circulo[15], 0);
	TextDrawSetOutline(circulo[15], 0);
	TextDrawBackgroundColor(circulo[15], 255);
	TextDrawFont(circulo[15], 4);
	TextDrawSetProportional(circulo[15], 1);
	
	circulo[16] = TextDrawCreate(340.000, 424.000, "LD_BEAT:chit");
	TextDrawTextSize(circulo[16], 5.000, 13.000);
	TextDrawAlignment(circulo[16], 1);
	TextDrawColor(circulo[16], -1);
	TextDrawSetShadow(circulo[16], 0);
	TextDrawSetOutline(circulo[16], 0);
	TextDrawBackgroundColor(circulo[16], 255);
	TextDrawFont(circulo[16], 4);
	TextDrawSetProportional(circulo[16], 1);
	
	circulo[17] = TextDrawCreate(344.000, 424.000, "LD_BEAT:chit");
	TextDrawTextSize(circulo[17], 5.000, 13.000);
	TextDrawAlignment(circulo[17], 1);
	TextDrawColor(circulo[17], -1);
	TextDrawSetShadow(circulo[17], 0);
	TextDrawSetOutline(circulo[17], 0);
	TextDrawBackgroundColor(circulo[17], 255);
	TextDrawFont(circulo[17], 4);
	TextDrawSetProportional(circulo[17], 1);
	
	circulo[18] = TextDrawCreate(344.000, 423.000, "LD_SPAC:white");
	TextDrawTextSize(circulo[18], 0.800, 8.000);
	TextDrawAlignment(circulo[18], 1);
	TextDrawColor(circulo[18], -1);
	TextDrawSetShadow(circulo[18], 0);
	TextDrawSetOutline(circulo[18], 0);
	TextDrawBackgroundColor(circulo[18], 255);
	TextDrawFont(circulo[18], 4);
	TextDrawSetProportional(circulo[18], 1);
}

hook OnGameModeInit() {
    CreateCircle();
    return 1;
}

hook OnPlayerDisconnect(playerid, reason) {
	DestroyPlayerCircleProgressAll(playerid);
    return 1;
}
